require "virtus"
require "rest-client"
require "adaptive_payments/version"
require "adaptive_payments/client"
require "adaptive_payments/abstract_request"
require "adaptive_payments/preapproval_request"
require "adaptive_payments/abstract_response"
require "adaptive_payments/preapproval_response"
